import { NavigationSidebar } from "@/components/navigation/navigation-sidebar";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Live Law",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <div className="h-full">
            <div className="md:flex h-full w-[72px] z-30 flex-col fixed inset-y-0">
              <NavigationSidebar />
            </div>
            <main className="md:pl-[72px]">{children}</main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
